// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5ISeAw4AvktIX1SgPlVrK-9dHAjhGH8',
    appId: '1:745833094851:web:d4268f6ea54c0ade2f0c76',
    messagingSenderId: '745833094851',
    projectId: 'voca-2ad05',
    authDomain: 'voca-2ad05.firebaseapp.com',
    databaseURL:
        'https://voca-2ad05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voca-2ad05.appspot.com',
    measurementId: 'G-ZGGCH68EJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9kinBXewIi58zVpvB1aBuCDAUhXZDNk',
    appId: '1:745833094851:android:23c745edadfe89352f0c76',
    messagingSenderId: '745833094851',
    projectId: 'voca-2ad05',
    databaseURL:
        'https://voca-2ad05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voca-2ad05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkamZTybGP1XRZdYQsaDhb6yB0IBeMnA',
    appId: '1:745833094851:ios:b1f76a9512be3d572f0c76',
    messagingSenderId: '745833094851',
    projectId: 'voca-2ad05',
    databaseURL:
        'https://voca-2ad05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voca-2ad05.appspot.com',
    iosBundleId: 'com.example.vocaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkamZTybGP1XRZdYQsaDhb6yB0IBeMnA',
    appId: '1:745833094851:ios:77ae882c7d3112962f0c76',
    messagingSenderId: '745833094851',
    projectId: 'voca-2ad05',
    databaseURL:
        'https://voca-2ad05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voca-2ad05.appspot.com',
    iosBundleId: 'com.example.vocaApp.RunnerTests',
  );
}
